---

- name: create /etc/certbot directory
  ansible.builtin.file:
    state: directory
    path: /etc/certbot
    mode: "0750"

- name: create /etc/certbot/domains directory
  ansible.builtin.file:
    state: directory
    path: /etc/certbot/domains
    mode: "0750"

# - name: merge certbot configuration between defaults and custom
#   ansible.builtin.set_fact:
#     multi_certbot_systemd: "{{ multi_certbot_defaults_systemd |
#       combine( multi_certbot_systemd, recursive=True ) }}"

# TODO
# only for nginx support
- name: ensure that ssl-dhparams.pem is present
  ansible.builtin.stat:
    path: "{{ multi_certbot_config.conf_directory }}/ssl-dhparams.pem"
  register: dhparams_exists

- name: Downloading recommended TLS parameters ...
  when:
    - dhparams_exists.stat is defined
    - not dhparams_exists.stat.exists
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/certbot/certbot/master/{{ item }}"
    dest: "{{ multi_certbot_config.conf_directory }}/{{ item | basename }}"
    mode: "0444"
  loop:
    - certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
    - certbot/certbot/ssl-dhparams.pem

- name: create well-known directory
  ansible.builtin.file:
    state: directory
    path: "{{ multi_certbot_config.well_known_directory }}"
    owner: "{{ multi_certbot_system.user }}"
    group: "{{ multi_certbot_system.group }}"
    mode: "0777"

- name: fix rights for well-known directory
  ansible.builtin.file:
    state: directory
    path: "{{ multi_certbot_config.www_directory }}"
    owner: "{{ multi_certbot_system.user }}"
    group: "{{ multi_certbot_system.group }}"
    mode: "0777"
    recurse: true
# -----------------------------------------------------------------------------

- name: ensure that domain certificates are present
  domain_certs:
    path: "{{ multi_certbot_config.conf_directory }}/live"
    file: fullchain.pem
    certificates: "{{ multi_certbot_tls_certificates }}"
  register: domain_certificates_exists

- name: define missing domains
  ansible.builtin.set_fact:
    multi_certbot_missing_domains: "{{ domain_certificates_exists.certificate_miss }}"

- name: missing certificates
  ansible.builtin.debug:
    msg: "{{ multi_certbot_missing_domains }}"

- name: IMPORTANT NOTE
  ansible.builtin.debug:
    msg: |
      The following task can have a long runtime.
      It depends on the response time of the web service or whether the DNS configuration is correct.

- name: create certificate with certbot certonly
  certbot:
    state: certonly
    arguments: "{{ multi_certbot_staging_args | default([]) }}"
    webroot_path: "{{ multi_certbot_config.www_directory }}"
    rsa_key_size: "{{ multi_certbot_config.rsa_key_size | int }}"
    domains: "{{ multi_certbot_tls_certificates }}"
    certbot_base_directory: "{{ multi_certbot_config.conf_directory }}"
    email: "{{ multi_certbot_config.email }}"
    test_cert: "{{ multi_certbot_test_cert | default('true') }}"
    dry_run: "{{ multi_certbot_dry_run | default('true') }}"
    auto_expand: "{{ multi_certbot_auto_expand | default('true') }}"
  register: create_certificates
  when:
    - multi_certbot_tls_certificates is defined
    - multi_certbot_tls_certificates | count > 0
    # - not multi_certbot_dry_run | default('true')
  ignore_errors: true

- name: d
  ansible.builtin.debug:
    msg: "{{ create_certificates }}"
  when:
    create_certificates.errors | default('0') | int > 0

# - name: create certificate
#   include_tasks: create_certificates.yml
#   loop: "{{ multi_certbot_missing_domains }}"
#   loop_control:
#     index_var: index
#     label: "certificate: {{ item }}"
#   when:
#     - multi_certbot_missing_domains is defined
#     - multi_certbot_missing_domains | count > 0

...
