---

- name: install requirements
  ansible.builtin.package:
    name: "{{ multi_certbot_requirements }}"
    state: present
  when:
    - multi_certbot_requirements | default([]) | count > 0

- name: install certbot
  ansible.builtin.package:
    name: certbot
    state: present

...
